In [42]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
# define a matrix
A = array([[1, 2], [3, 4], [8, 6]])
print(A)

[[1 2]
 [3 4]
 [8 6]]


In [43]:
# calculate the mean of each column
M = mean(A.T, axis=1)
print(M)

[4. 4.]


In [44]:
# center columns by subtracting column means
C = A - M
print(C)

[[-3. -2.]
 [-1.  0.]
 [ 4.  2.]]


In [48]:
# calculate covariance matrix of centered matrix
V = cov(C.T)
print(V)

[[13.  7.]
 [ 7.  4.]]


In [49]:
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)

[[ 0.87771225 -0.47918807]
 [ 0.47918807  0.87771225]]
[16.82165849  0.17834151]


In [50]:
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[-3.59151289 -0.3178603 ]
 [-0.87771225  0.47918807]
 [ 4.46922514 -0.16132777]]
